### PR TITLE
Roster per section

### PR DESCRIPTION
**Pull request by sonjak7**
## Description
Allow teach to see students in course by section

### Special Notes
- Added section and enrollment hooks
-  Currently relies on "modify-enrollment-info" branch on backend

### How has this been tested?
Manual testing

## Requirements
Fill out the checkboxes below, verifying that all the requirements have been satisfied:
- [ ] Have I written new tests to show my code works?
- [ ] Do all other tests still work?
- [ ] Have I documented where necessary (technical docs, how to docs, etc.)?
- [ ] Have I requested at least 1 reviewer?
- [ ] Have I left comments so my work is easy to understand?
- [ ] Have I looked over my code again to weed out any mistakes I may have made or details missed?
- [ ] Does my work reflect all the needs of this given task?

### CODE REVIEW

**Comment by METrimble** [comment]
Looks great! I ran it on my local computer (everything is pulled and up-to-date) but I wasn't able to get http://localhost:3000/1/roster/1 to run. When I open the page, I get the following errors in the console: 

```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Enrollments`. See https://reactjs.org/link/warning-keys for more information.
    at Enrollments (http://localhost:3000/static/js/bundle.js:4769:66)
    at Outlet (http://localhost:3000/static/js/bundle.js:60571:26)
    at Outlet (http://localhost:3000/static/js/bundle.js:60571:26)
    at Outlet (http://localhost:3000/static/js/bundle.js:60571:26)
    at div
    at Navigation (http://localhost:3000/static/js/bundle.js:1706:81)
    at Routes (http://localhost:3000/static/js/bundle.js:60654:5)
    at App (http://localhost:3000/static/js/bundle.js:78:106)
    at Router (http://localhost:3000/static/js/bundle.js:60594:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:59527:5)
    at Provider (http://localhost:3000/static/js/bundle.js:57065:5)

Uncaught TypeError: Cannot read properties of undefined (reading 'firstName')
    at StudentListItem (StudentListItem.js:4:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)

The above error occurred in the <StudentListItem> component:
    at StudentListItem (http://localhost:3000/static/js/bundle.js:1623:22)
    at ul
    at Enrollments (http://localhost:3000/static/js/bundle.js:4769:66)
    at Outlet (http://localhost:3000/static/js/bundle.js:60571:26)
    at Outlet (http://localhost:3000/static/js/bundle.js:60571:26)
    at Outlet (http://localhost:3000/static/js/bundle.js:60571:26)
    at div
    at Navigation (http://localhost:3000/static/js/bundle.js:1706:81)
    at Routes (http://localhost:3000/static/js/bundle.js:60654:5)
    at App (http://localhost:3000/static/js/bundle.js:78:106)
    at Router (http://localhost:3000/static/js/bundle.js:60594:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:59527:5)
    at Provider (http://localhost:3000/static/js/bundle.js:57065:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

Is this just a my end thing?

**Review by ghost — APPROVED** [review]
This looks great. I too implemented the useSection hook not realizing you would need it too and our code is almost identical. Love it, thank you Sanjay

**Comment by ghost** [comment]
@METrimble @sonjak7, just seeing Elayne's comment now. It might be worth testing this endpoint on Postman to make sure it's not returning duplicate enrollment records? It looks like Sanjay has each student in the list keyed by the enrollment id so that's the only thing I can think of to be throwing that error on StudentListItem. Thoughts?

**Comment by sonjak7** [comment]
@mphotchkiss @METrimble I think the issue there was multiple empty tags `<></>` in a `<ul>`, which I guess you can't do in react, so I put the enrollment.id as a key for that. 

I wasn't getting the second & third error in the console though `Uncaught TypeError: Cannot read properties of undefined (reading 'firstName')`. I wonder if this change fixes that on your side?

**Comment by ghost** [comment]
@sonjak7, that other error would be a result of Elayne not having the BE branch that matches this one, so you're good to merge I think. It works for me

**Pull request merged**
